### ISSUE TITLE
Method not found: 'Void SimpleBrowser.Browser..ctor

### ISSUE THREAD

**Issue by niks-** [Teun/SimpleBrowser.WebDriver#31]
*Environment*
* SimpleBrowser.WebDriver 0.5.33 
* SimpleBrowser 0.5.61.0
* Selenium.WebDriver 2.46.0

*Steps*
I am trying to initialize new SimpleBrowserDriver
```
protected static IWebDriver Driver { get; set; }
private static void CreateDriver(string browser)
{
if (browser == null)
            {
                 Driver = new SimpleBrowserDriver();
            }
...
 }
```

*Issue*
Error appears
````
 System.MissingMethodException : Method not found: 'Void SimpleBrowser.Browser..ctor(SimpleBrowser.Network.IWebRequestFactory, System.String)'.
```

*StackTrace*
```
   at SimpleBrowser.WebDriver.BrowserWrapper..ctor()
   at SimpleBrowser.WebDriver.SimpleBrowserDriver..ctor()
   at PartnerDashboardUI.Framework.PageObject.CreateDriver(String browser) in PageObject.cs: line 383
   at PartnerDashboardUI.Framework.PageObject.StartBrowser() in PageObject.cs: line 257
   at PartnerDashboardUI.Test.SetUpFixture.SuiteSetUp() in SetUpFixture.cs: line 40
```

**Comment by Teun** [comment]
Mmm. Must be a version issue with Webdriver. But 2.46.0 should be backward compatible with 2.42.0. Will look into this soon. Thanks for notifying.

**Comment by niks-** [comment]
I've already tried WebDriver 2.42.0. Actually, issue was found on WebDriver 2.42.0 initially.
I thought that it could be problem with WebDriver and updated it to 2.46.0.

**Comment by Teun** [comment]
That's odd. I tried to reproduce on your exact version and got exactly your
error message. Then I tried again your using the versions that come with
0.5.33 as minimum dependencies and it just worked. What is your framework
version?

T

2015-06-09 11:56 GMT+02:00 niks- <notifications@github.com>:

**Comment by niks-** [comment]
I've verified again with WebDriver 2.42. Have the same issue. Attached few screenshot with packages I have installed.
![sc_0408](https://cloud.githubusercontent.com/assets/8697655/8056455/f7ac39d6-0eb0-11e5-8b28-ed652d228042.gif)
![sc_0407](https://cloud.githubusercontent.com/assets/8697655/8056456/f7c1de26-0eb0-11e5-81ca-6897dfcabed5.gif)
![sc_0406](https://cloud.githubusercontent.com/assets/8697655/8056458/f7e5f57c-0eb0-11e5-9c3a-3efc6ea3849b.gif)

>> What is your framework version?
What framework are you asking about? If you are about test framework - I use Nunit v2.6.4

Feel free to ask me about everything what you need.

**Comment by Teun** [comment]
Thanks. I meant ".NET framework version".

**Comment by niks-** [comment]
The project is configured for .Net Framework 4.0. 
Have the following on my workstation

C:\Windows\system32>wmic /namespace:\\root\cimv2 path win32_product where "name like '%%.NET%%'" get version
Version
4.5.50932
4.0.20710.0
3.0.40218.0
4.5.50710
4.5.50932
4.5.21005
4.1.20219.0
3.0.50813.0
4.0.20710.0
2.0.60926.0
4.5.50710
4.0.20710.0
1.0.20710.0
4.1.21001.0
4.1.20219.0
4.0.40804.0
4.1.21001.0
2.0.50217.0
4.5.21005
3.11.50727
4.1.20219.0
5.0.11001.0
3.0.20406.0
2.0.20525.0
2.0.20710.0
4.0.30319
2.0.3010.0
1.0.20710.0
3.0.30710.0
3.0.30710.0
2.0.20716.0
2.0.20710.0
4.5.50938
4.1.20219.0
4.5.51641
1.0.20105.0
1.0.20105.0
4.0.20710.0

**Comment by Teun** [comment]
Have been able to reproduce: 

New console app, using Nuget:

    Install-Package SimpleBrowser.WebDriver

Results in 

    Successfully added 'SimpleBrowser 0.5.42.0' to ConsoleApplication2.
    Successfully added 'Selenium.WebDriver 2.42.0' to ConsoleApplication2. 
    Successfully added 'SimpleBrowser.WebDriver 0.5.33' to ConsoleApplication2.

Then this code runs fine: 

       var w = new SimpleBrowserDriver();
       w.Navigate().GoToUrl("http://www.github.com");
       // writes "https://github.com"
       Console.WriteLine(w.Url);


Then by running 

     Update-Package SimpleBrowser -Version 0.5.61

It breaks. So Selenium is OK, it is SimpleBrowser that has a non-backwards-compatible change. Investigating further.

**Comment by Teun** [comment]
OK, a new **optional** parameter was added to the constructor of the SimpleBrowser class. This is backward compatible, but apparently only at compile-time. I wasn't aware that optional arguments do not provide binary compatibility, but there you go. So SimpleBrowser broke binary compatibility in a minor version upgrade. I will update SimpleBrowser.WebDriver ASAP to be compiled against a current version.

Learned something.

**Comment by Teun** [comment]
I've published a newer version to NuGet. @niks- can you test?

**Comment by niks-** [comment]
It works now. Thanks!

**Comment by fredgate** [comment]
I have the issue with the following versions 
  SimpleBrowser 0.5.46.0
  SimpleBrowser.WebDriver 0.5.34
  Selenium.WebDriver 2.48.0

The code is
```
var driver = new SimpleBrowserDriver();
```

The error message is
```
MissingMethodException : 'Void SimpleBrowser.Browser..ctor(SimpleBrowser.Network.IWebRequestFactory, System.String, System.Collections.Generic.List`1<SimpleBrowser.Browser>)'.

   à SimpleBrowser.WebDriver.BrowserWrapper..ctor()
   à SimpleBrowser.WebDriver.SimpleBrowserDriver..ctor()
   à MyTestProject....

```

**Comment by Teun** [comment]
Thanks for your report. Looks bad. I have to investigate.

**Comment by Teun** [comment]
Solved: the latest stable version of the driver was OK and could work with the latest version of SimpleBrowser (read the above for more info), but I forgot to update the lowest required version in the nuspec. Result: it worked OK if you manually updated to the latest version of SimpleBrowser, but if you were working with 0.5.46 as the nuspec suggested, it was still broken. 

Thanks again for reporting. Many people must have walked away confused or accidentally fixed it by updating SimpleBrowser.

Your fix Update-Package SimpleBrowser.WebDriver. This will also update SimpleBrowser.
